irclogs/irc/urls.py
from django.conf.urls.defaults import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.channels_list, name='channels_list'),

    url(r'^(?P<channel>.+)/$', views.channel_detail, name='channel_detail'),

    url(r'^(?P<channel>.+)/links/$',
        views.channel_links, name='channel_links'),

    # Stats: frequency / evolution, active users, # of users
    url(r'^(?P<channel>.+)/stats/$',
        views.channel_stats, name='channel_stats'),
)

irclogs/irc/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Channel(models.Model):
    name = models.CharField(_('Name'), max_length=255, db_index=True)
    public = models.BooleanField(_('Is public'), default=False)

    def __unicode__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('channel_detail', args=[self.name[1:]])

    def is_public(self):
        return self.name.startswith('#')


class Event(models.Model):
    JOIN = 'JOIN'
    QUIT = 'QUIT'
    PART = 'PART'
    NICK = 'NICK'
    MODE = 'MODE'
    ME = 'ME'
    CHAT = 'CHAT'
    TYPES = (
        (JOIN, _('Join')),
        (QUIT, _('Quit')),
        (PART, _('Part')),
        (NICK, _('Nick')),
        (MODE, _('Mode')),
        (ME, _('Me')),
        (CHAT, _('Chat')),
    )

    TYPES_SUBST = {
        JOIN: u'*** Joins:',
        QUIT: u'*** Quits:',
        PART: u'*** Parts:',
    }
    channel = models.ForeignKey(Channel, verbose_name=_('Channel'),
                                related_name='events')
    event_type = models.CharField(_('Event type'), choices=TYPES,
                                  db_index=True, max_length=10)
    nickname = models.CharField(_('Nickname'), max_length=255, db_index=True)
    content = models.TextField(_('Content'))
    timestamp = models.DateTimeField(_('Date'), db_index=True)

    # Where is this in the log?
    filename = models.CharField(_('Filename'), max_length=255, db_index=True)
    lineno = models.PositiveIntegerField(_('Lineno'), db_index=True)

    class Meta:
        ordering = ['-timestamp']
        unique_together = ('filename', 'lineno')

    def __unicode__(self):
        """Displays what appears in the log"""
        if self.event_type in self.TYPES_SUBST:
            template = u'%%s %s %%s %%s' % self.TYPES_SUBST[self.event_type]
        elif self.event_type == self.ME:
            template = u'%s * %s %s'
        elif self.event_type in (self.NICK, self.MODE):
            template = u'%s *** %s %s'
        else:
            template = u'%s <%s> %s'
        date = u'[%s]' % self.timestamp.strftime('%H:%M')
        return template % (date, self.nickname, self.content)


class Link(models.Model):
    event = models.ForeignKey(Event, verbose_name=_('Link'),
                              related_name='links')
    url = models.URLField(_('URL'), verify_exists=False, max_length=400)

    def __unicode__(self):
        return u'%s' % self.url

irclogs/irc/views.py
import datetime
import re
import time

from django.shortcuts import get_object_or_404
from django.views import generic

from .models import Channel, Event, Link

DATE_RE = re.compile(r'^(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})$')

class PublicChannelsMixin(object):
    def get_queryset(self):
        qs = super(PublicChannelsMixin, self).get_queryset()
        if self.request.user.is_authenticated():
            return qs
        return qs.filter(public=True)


class Channels(PublicChannelsMixin, generic.ListView):
    context_object_name = 'channels'
    model = Channel
channels_list = Channels.as_view()


class ChannelView(PublicChannelsMixin, generic.DetailView):
    model = Channel

    def get_object(self):
        qs = super(ChannelView, self).get_queryset()
        return get_object_or_404(qs, name='#' + self.kwargs['channel'])

    def get_context_data(self, **kwargs):
        ctx = super(ChannelView, self).get_context_data(**kwargs)
        filter_date = datetime.datetime.now()
        if 'date' in self.request.GET:
            match = DATE_RE.match(self.request.GET['date'])
            if match:
                timetuple = map(int, match.group(1, 2, 3)) + [0, 0, 0, 0, 0, 0]
                timestamp = time.mktime(timetuple)
                filter_date = datetime.datetime.fromtimestamp(timestamp)
        events = self.object.events.filter(timestamp__year=filter_date.year,
                                           timestamp__month=filter_date.month,
                                           timestamp__day=filter_date.day)
        ctx.update({
            'channels': self.get_queryset(),
            'events': events.reverse(),
            'date': filter_date,
        })
        before = filter_date - datetime.timedelta(days=1)
        after = filter_date + datetime.timedelta(days=1)
        if self.object.events.filter(timestamp__lt=before).exists():
            ctx['before'] = before
        if self.object.events.filter(timestamp__gt=after):
            ctx['after'] = after
        return ctx


class ChannelDetail(ChannelView):
    pass
channel_detail = ChannelDetail.as_view()


class ChannelLinks(generic.ListView):
    model = Link
channel_links = ChannelLinks.as_view()


class Stats(ChannelView):
    pass
channel_stats = Stats.as_view()

irclogs/irc/templates/irc/base.html
{% extends "base.html" %}

irclogs/irc/templates/irc/channel_detail.html
{% extends "irc/channel_list.html" %}
{% load i18n staticfiles %}

{% block title %}{% trans "Channels" %}{% endblock %}

{% block frame %}
	{% if not events %}
		<h2 class="date">
			{% if before %}
				<a href="?date={{ before|date:"Y-m-d" }}">&lsaquo;</a>
			{% endif %}
			<span id="datefield">{{ date|date:"Y-m-d" }}</span>
			{% if after %}
				<a href="?date={{ after|date:"Y-m-d" }}">&rsaquo;</a>
			{% endif %}
		</h2>
	{% endif %}
	{% spaceless %}
		{% for event in events %}
			{% ifchanged event.timestamp.day %}
				<h2 class="date">
					{% if before %}
						<a href="?date={{ before|date:"Y-m-d" }}">&lsaquo;</a>
					{% endif %}
					<span id="datefield">{{ event.timestamp|date:"Y-m-d" }}</span>
					{% if after %}
						<a href="?date={{ after|date:"Y-m-d" }}">&rsaquo;</a>
					{% endif %}
				</h2>
			{% endifchanged %}
			{% ifchanged event.timestamp.minute %}
				{% if event.event_type == event.CHAT or event.event_type == event.ME %}
					<div class="nick date">&nbsp;</div>
					<div class="chat date"><span class="date">{{ event.timestamp|date:"H:i" }}</span></div>
				{% endif %}
			{% endifchanged %}
			{% if event.event_type == event.CHAT %}
				<div class="nick">{{ event.nickname }}</div>
				<div class="chat">{{ event.content|urlize }}</div>
			{% endif %}
			{% if event.event_type == event.ME %}
				<div class="nick">*</div>
				<div class="chat">{{ event.nickname }} {{ event.content|urlize }}</div>
			{% endif %}
		{% endfor %}
	{% endspaceless %}
{% endblock %} 

{% block extracontent %}{{ block.super }}
	<script type="text/javascript" src="{% static "irc/js/prototype.js" %}"></script>
	<script type="text/javascript" src="{% static "irc/js/calendarview.js" %}"></script>
	<script type="text/javascript">
		function prependZero(num) {
			num = num.toString();
			if (num.length == 1)
				num = '0' + num;
			return num;
		}

		window.onload = function() {
			Calendar.setup({
				dateField: 'datefield',
				triggerElement: 'datefield',
				closeHandler: function(klass) {
					qs = klass.date.getFullYear() + '-' + prependZero(klass.date.getMonth() + 1) +  '-' + prependZero(klass.date.getDate());
					href = window.location.href.split('?')[0];
					href += '?date=' + qs;
					window.location.href = href;
				}
			});
		}
	</script>
{% endblock %}

irclogs/irc/templates/irc/channel_list.html
{% extends "irc/base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Channels" %}{% endblock %}

{% block content %}
	<h1>
		{% if object %}
			{{ object }}
		{% else %}
			{% trans "Channels" %}
		{% endif %}
	</h1>
	<ul class="channels">{% spaceless %}
		{% for channel in channels %}
			{% if channel.is_public or user.is_superuser %}
				<li{% if channel == object %} class="selected"{% endif %}><a href="{{ channel.get_absolute_url }}">{{ channel }}</a></li>
			{% endif %}
		{% endfor %}
	{% endspaceless %}</ul>
	<div class="frame">
		{% block frame %}{% endblock %}
	</div>
{% endblock %} 